### ISSUE TITLE
Modifiche

### ISSUE THREAD

**Issue by angy89** [Abelarm/BioInf_Project#1]
Quando clicco sul nanomateriale, vorrei sapere i tre pallini a quali oggetti si riferiscono (drug, chemical o disease) e potresti mettere la grandezza dei tre nodi pari al suo degree, cosi uno si fa un'idea di ogni nanomateriale a che categoria di oggetti è maggiormente collegata, magari normalizzando in base al numero di item in ogni categoria. Poi quando passo il mouse sui nodi più interni, non vedo le labels come per i nanomateriali. In più vorrei aggiungere le connessioni tra i nanomateriali, in modo che il grafo iniziale non siano solo i 29 pallini scollegati tra di loro.

**Comment by Abelarm** [comment]
DONE!
