### ISSUE TITLE
Bug e Modifiche

### ISSUE THREAD

**Issue by angy89** [Abelarm/BioInf_Project#2]
- Andare all'università il 7 gennaio
- I nodi e gli archi a volte restano appesi. 
- I nodi interni a drug, chemical e disease dovrebbero restare marcati quando ci passi il mouse e ci clicchi sopra, invece i tre nodi esterni devono mantenere la grandezza in base al degree
- il degree deve essere normalizzato in relazione al numero di oggetti per categoria
- Per i tre nodi, invece di scrivere Chem/Phar/DiseOf nano.. scriveteci Chemical, Drug e Disease col numero di oggetti (tipo 6 Drugs)

**Comment by Abelarm** [comment]
Domani vengo
risolto
not yet
ho fatto (#numelementi_tot/#elementi) che normalizzazione avevi in mente
aggiustato, ... però toglierei il numero perchè si trova sempre 20 Dise, 99 Drugs, 193 Chem

**Comment by angy89** [comment]
- non sei venuto! xD
- ok
- ok
- Ad esempio per ogni nanomateriale mi dici la percentuale di drugs, chemical e disease connesse a lui. Tipo il 20% delle disease nel dataset è connessa a MWCNT. Fai (ndrug_connesse \* 100)/ndrug_totale
- se si trova sempre lo stesso numero ci starà qualche errore, perchè nel clustering che ho fatto io mi trovo numeri diversi associati a ogni nanomateriale. L'errore può essere nel tuo script o nel json che ti ho dato. Devo controllare questa cosa ma oggi non ho avuto tempo...
