### ISSUE TITLE
archi da aggiungere tra i nanomateriali

### ISSUE THREAD

**Issue by angy89** [Abelarm/BioInf_Project#3]
Lo spessore degli archi dovrebbe essere proporzionale al peso che hanno. Inoltre, quelli positivi dovrebbero essere rossi, mentre quelli negativi verdi.

{"source":0,"target":1,"value":4.43790692114177},
{"source":0,"target":3,"value":-1.50695398267579},
{"source":0,"target":17,"value":-1.05476262863406},
{"source":0,"target":26,"value":-1.40538606193053},
{"source":0,"target":27,"value":-1.09782809654766},
{"source":1,"target":10,"value":4.29132965849901},
{"source":1,"target":16,"value":-1.20020278161897},
{"source":3,"target":12,"value":-1.14254705842359},
{"source":4,"target":9,"value":3.56772585428173},
{"source":4,"target":12,"value":5.19759180448495},
{"source":4,"target":13,"value":3.05898297253507},
{"source":4,"target":16,"value":-1.08586960333752},
{"source":6,"target":12,"value":2.88754580322601},
{"source":7,"target":26,"value":-1.38406366334636},
{"source":9,"target":13,"value":5.0542088654678},
{"source":9,"target":14,"value":10.8049099192233},
{"source":10,"target":24,"value":-1.29320243269346},
{"source":12,"target":13,"value":4.57157659911705},
{"source":13,"target":14,"value":5.14544517464535},
{"source":13,"target":16,"value":-1.38680196156656},
{"source":13,"target":21,"value":3.38435652266791},
{"source":13,"target":22,"value":5.5458439940923},
{"source":14,"target":18,"value":2.74310225665253},
{"source":15,"target":16,"value":2.76942587609609},
{"source":15,"target":17,"value":4.97432238921178},
{"source":15,"target":24,"value":-1.16208825258496},
{"source":19,"target":20,"value":5.22356560424663},
{"source":24,"target":25,"value":4.70790623749152},
{"source":24,"target":26,"value":5.94264806898708},
{"source":24,"target":27,"value":3.8883904473592},
{"source":24,"target":28,"value":6.86957074822737},
{"source":25,"target":26,"value":4.54077092024467},
{"source":25,"target":27,"value":2.85841927057944},
{"source":25,"target":28,"value":4.41980544983266},
{"source":26,"target":27,"value":5.92816308674719},
{"source":26,"target":28,"value":5.95650817390348},
{"source":27,"target":28,"value":3.71004226415445},

**Comment by Abelarm** [comment]
fatto chiudo

**Comment by angy89** [comment]
Io gli archi tra i nanomateriali non li vedo...

**Comment by Abelarm** [comment]
perchè non ho uppato il JSON U.U
Hai modificato il tuo?

**Comment by angy89** [comment]
no, non l'ho modificato xD carica il tuo..

**Comment by Abelarm** [comment]
done!
