### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by angy89** [Abelarm/BioInf_Project#4]
- Mancano colori e spessore sugli archi interni.
- Il grafo non si aggiorna quando cambio gli slider

**Comment by angy89** [comment]
Aggiungere la legenda anche per gli altri oggetti e per il colore degli archi
Implementare la funzione che evidenzia i vicini di un nodo

**Comment by angy89** [comment]
Quando clicco su un arco, vorrei vedere il peso dell'arco

**Comment by angy89** [comment]
Implementare il trascinamento e il fissaggio di un nodo, creando il listener sul ctrl+click

**Comment by Abelarm** [comment]
TUTTOFATTO
